[workspace]
resolver = "2"
members = ["monkey-lex", "monkey-repl"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[workspace.dependencies]
casey = "0.4.0"
nom = "7.1.3"
monkey-lex.path = "./monkey-lex"
